domain    = "clutter/clutter.pddl"
problem   = "clutter/clutter_pb2.pddl"
scene     = "clutter/clutter_2.xml"
objdir    = "clutter/"
semantics = "clutter.lua"
output    = "clutter2_solution.json"
perf_file = "clutter_2.csv"
params    = "params.toml"
blacklist = "models/pr2_collision_blacklist.csv"
