domain    = "~/projects/research/tamp/src/planet/test_scenarios/clutter/clutter.pddl"
problem   = "~/projects/research/tamp/src/planet/test_scenarios/clutter/clutter_full.pddl"
scene     = "~/projects/research/tamp/src/planet/test_scenarios/clutter/clutter.xml"
objdir    = "~/projects/research/tamp/src/planet/test_scenarios/clutter/"
semantics = "clutter.lua"
output    = "clutter_solution.json"
perf_file = "clutter_full.csv"
params    = "params.toml"
blacklist = "models/pr2_collision_blacklist.csv"
